baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'GdR - SDL'
    


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true